<?php

namespace Tgc\EditContentBundle\Repository;

/**
 * TextEditableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextEditableRepository extends \Doctrine\ORM\EntityRepository
{
  function findBySlugs($slugs)
  {
    $qb = $this->createQueryBuilder('t');
    $result = $qb->where($qb->expr()->in('t.slug', $slugs))
      ->indexBy('t', 't.slug')
      ->getQuery()
      ->getResult();
    return $result;
  }
}
